name: Publish to NPM on Release

on:
  release:
    types: [created]

env:
  NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        cd widgets
        npm install
      
    - name: Build
      run: |
        cd widgets
        npm run build
      
    - name: Publish to NPM
      env:
        NODE_AUTH_TOKEN: ${{ env.NPM_AUTH_TOKEN }}
      run: |
        cd widgets
        echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
        npm publish
